tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: my_dev_db
      schema: my_dev_schema
      warehouse: tasty_bytes_dbt_wh
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: my_prod_db
      schema: my_prod_schema
      warehouse: tasty_bytes_dbt_wh
