tasty_bytes:
  target: silver
  outputs:
    silver:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: TASTY_BYTES_DBT_DB_TEST
      schema: silver
      warehouse: tasty_bytes_dbt_wh
    gold:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: TASTY_BYTES_DBT_DB_TEST
      schema: gold
      warehouse: tasty_bytes_dbt_wh
