tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: TEST_DBT_INTEGRATION
      schema: dev
      warehouse: dbt_wh
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: TEST_DBT_INTEGRATION
      schema: prod
      warehouse: dbt_wh